# Copyright (c) 2019-2021 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 

dependencies:
  # Prometheus
  - name: prometheus
    version: 15.10.5
    condition: prometheus.enabled
    repository: https://prometheus-community.github.io/helm-charts
  # Grafana
  - name: grafana
    version: 6.30.3
    condition: grafana.enabled
    repository: https://grafana.github.io/helm-charts
  # HPA Metrics
  - name: metrics-server
    version: 3.8.3
    condition: metrics-server.enabled
    repository: https://kubernetes-sigs.github.io/metrics-server
  # Ingress Controller
  - name: ingress-nginx
    version: 4.2.0
    condition: ingress-nginx.enabled
    repository: https://kubernetes.github.io/ingress-nginx
  # cert-manager
  - name: cert-manager
    version: 1.8.2
    condition: cert-manager.enabled
    repository: https://charts.jetstack.io
  # jenkins
  - name: jenkins
    version: 2.1.0
    condition: jenkins.enabled
    repository: https://charts.helm.sh/stable
