# https://github.com/helm/charts/blob/master/stable/metrics-server/README.md
metrics-server:
  enabled: true
  args: [
    # not recommended in production
    --kubelet-insecure-tls,
    --kubelet-preferred-address-types=InternalIP
  ]

# https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/README.md
# https://artifacthub.io/packages/helm/prometheus-community/prometheus
prometheus:
  enabled: true
  extraScrapeConfigs: |
    - job_name: 'ingress-nginx'
      metrics_path: /metrics
      scrape_interval: 5s
      static_configs:
        - targets:
          - {{ .Release.Name }}-ingress-nginx-controller-metrics:9913


# https://github.com/kubernetes-sigs/service-catalog/blob/master/charts/catalog/README.md
catalog:
  enabled: true

# https://kubernetes.github.io/ingress-nginx/
# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
ingress-nginx:
  enabled: true
  controller:
    metrics:
      enabled: true

# https://github.com/jetstack/cert-manager/blob/master/README.md
# https://artifacthub.io/packages/helm/jetstack/cert-manager
cert-manager:
  enabled: true
  installCRDs: true

# https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md
# https://artifacthub.io/packages/helm/grafana/grafana
grafana:
  enabled: true
  dashboards:
    default:
      k8s-cluster:
        gnetId: 7249
        revision: 1
        datasource: Prometheus
      k8s-cluster-metrics:
        gnetId: 11663
        revision: 1
        datasource: Prometheus
      k8s-cluster-metrics-simple:
        gnetId: 6417
        revision: 1
        datasource: Prometheus
      k8s-pods-monitoring:
        gnetId: 13498
        revision: 1
        datasource: Prometheus
      k8s-memory:
        gnetId: 13421
        revision: 1
        datasource: Prometheus
      k8s-networking:
        gnetId: 12658
        revision: 1
        datasource: Prometheus
      k8s-pods:
        gnetId: 6336
        revision: 1
        datasource: Prometheus
      spring-boot:
        gnetId: 12464
        revision: 2
        datasource: Prometheus
      nginx-ingress-controller:
        gnetId: 9614
        revision: 1
        datasource: Prometheus
      oci-compute:
        gnetId: 13596
        revision: 1
        datasource: Oracle Cloud Infrastructure Metrics
      oci-oke:
        gnetId: 13594
        revision: 1
        datasource: Oracle Cloud Infrastructure Metrics
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  sidecar:
    datasources:
      enabled: true
      label: grafana_datasource
    dashboards:
      enabled: true
      label: grafana_dashboard
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
  persistence:
    enabled: true
  plugins:
    - oci-logs-datasource
    - oci-metrics-datasource
    - grafana-kubernetes-app
    - grafana-worldmap-panel
    - grafana-piechart-panel
    - btplc-status-dot-panel
    - grafana-github-datasource

# https://github.com/helm/charts/blob/master/stable/jenkins/README.md
jenkins:
  enabled: false
  master:
    serviceType: ClusterIP
    jenkinsUriPrefix: "/jenkins"
    ingress:
      # enable ingress only if the ingress-controller `nginx-ingress` is enabled.
      enabled: true
      paths:
        - path: /jenkins
          backend:
            serviceName: >-
              {{ template "jenkins.fullname" . }}
            servicePort: 8080
      apiVersion: "networking.k8s.io/v1beta1"
      labels: {}
      annotations:
        kubernetes.io/ingress.class: nginx
    installPlugins:
      - kubernetes:1.26.1
      - workflow-job:2.39
      - workflow-aggregator:2.6
      - credentials-binding:1.23
      - git:4.2.2
      - configuration-as-code:1.41
      - blueocean:1.23.2
    